#include<stdio.h>
int main(void)
{
    printf("歡迎來到發票兌獎系統\n");
    int special[8],spec[8],head[3][8],extra[3][3],receipt[8];              //special 特別獎     spec 特獎    head 頭獎    extra 增開六獎
    int temp,Temp[8],i,j,prize;                                      //temp 儲存輸入的數字     Temp[]儲存之前輸入的數或後三碼      prize  是否中獎

    while(1)                                                                //設定特別獎中獎號碼
    {
        printf("提示:若輸入未滿8位數,系統會自動在前方補上0直到滿8位數\n");
        printf("請輸入特別獎中獎號碼\n");
        scanf("%d",&temp);
        if(temp%100000000!=temp)                                            //判斷輸入數字位數
        {
            printf("特別獎號碼不可大於8位數,請重新輸入\n");
            continue;
        }
        printf("輸入成功\n");
        Temp[0]=temp;
        for(i=7;i>=0;i--)                                                   //儲存中獎號碼
        {
            special[i]=temp%10;
            temp=temp/10;
        }
        break;
    }
    while(1)                                                                //設定特獎中獎號碼
    {
        printf("請輸入特獎中獎號碼\n");
        scanf("%d",&temp);
        if(temp%100000000!=temp)                                            
        {
            printf("特獎號碼不可大於8位數,請重新輸入\n");
            continue;
        }
        if(temp==Temp[0])                                                   //判斷是否與前面獎項重複
        {
            printf("特獎號碼不可與特別獎相同,請重新輸入\n");
            continue;
        }
        printf("輸入成功\n");
        Temp[1]=temp;
        for(i=7;i>=0;i--)
        {
            spec[i]=temp%10;
            temp=temp/10;
        }
        break;
    }
    while(1)                                                                //設定第一組頭獎中獎號碼
    {
        printf("請輸入第一組頭獎中獎號碼\n");
        scanf("%d",&temp);
        if(temp%100000000!=temp)
        {
            printf("頭獎號碼不可大於8位數,請重新輸入\n");
            continue;
        }
        if(temp==Temp[0])
        {
            printf("頭獎號碼不可與特別獎相同,請重新輸入\n");
            continue;
        }
        if(temp==Temp[1])
        {
            printf("頭獎號碼不可與特獎相同,請重新輸入\n");
            continue;
        }
        printf("輸入成功\n");
        Temp[2]=temp%1000;
        for(i=7;i>=0;i--)
        {
            head[0][i]=temp%10;
            temp=temp/10;
        }
        break;
    }
    while(1)                                                                //設定第二組頭獎中獎號碼
    {
        printf("請輸入第二組頭獎中獎號碼\n");
        scanf("%d",&temp);
        if(temp%100000000!=temp)
        {
            printf("頭獎號碼不可大於8位數,請重新輸入\n");
            continue;
        }
        if(temp==Temp[0])
        {
            printf("頭獎號碼不可與特別獎相同,請重新輸入\n");
            continue;
        }
        if(temp==Temp[1])
        {
            printf("頭獎號碼不可與特獎相同,請重新輸入\n");
            continue;
        }
        if(temp%1000==Temp[2])
        {
            printf("各組頭獎號碼末三碼不可相同,請重新輸入\n");
            continue;
        }
        printf("輸入成功\n");
        Temp[3]=temp%1000;
        for(i=7;i>=0;i--)
        {
            head[1][i]=temp%10;
            temp=temp/10;
        }
        break;
    }
    while(1)                                                                //設定第三組頭獎中獎號碼
    {
        printf("請輸入第三組頭獎中獎號碼\n");
        scanf("%d",&temp);
        if(temp%100000000!=temp)
        {
            printf("頭獎號碼不可大於8位數,請重新輸入\n");
            continue;
        }
        if(temp==Temp[0])
        {
            printf("頭獎號碼不可與特別獎相同,請重新輸入\n");
            continue;
        }
        if(temp==Temp[1])
        {
            printf("頭獎號碼不可與特獎相同,請重新輸入\n");
            continue;
        }
        if(temp%1000==Temp[2] || temp%1000==Temp[3])
        {
            printf("各組頭獎號碼末三碼不可相同,請重新輸入\n");
            continue;
        }
        printf("輸入成功\n");
        Temp[4]=temp%1000;
        for(i=7;i>=0;i--)
        {
            head[2][i]=temp%10;
            temp=temp/10;
        }
        break;
    }
    while(1)                                                                //設定第一組增開六獎中獎號碼
    {
        printf("請輸入第一組增開六獎中獎號碼\n");
        scanf("%d",&temp);
        if(temp%1000!=temp)
        {
            printf("增開六獎號碼不可大於3位數,請重新輸入\n");
            continue;
        }
        if(temp==Temp[2] || temp==Temp[3] || temp==Temp[4])
        {
            printf("增開六獎不可與頭獎號碼末三碼相同,請重新輸入\n");
            continue;
        }
        printf("輸入成功\n");
        Temp[5]=temp;
        for(i=2;i>=0;i--)
        {
            extra[0][i]=temp%10;
            temp=temp/10;
        }
        break;
    }
    while(1)                                                                //設定第二組增開六獎中獎號碼
    {
        printf("請輸入第二組增開六獎中獎號碼\n");
        scanf("%d",&temp);
        if(temp%1000!=temp)
        {
            printf("增開六獎號碼不可大於3位數,請重新輸入\n");
            continue;
        }
        if(temp==Temp[2] || temp==Temp[3] || temp==Temp[4])
        {
            printf("增開六獎不可與頭獎號碼末三碼相同,請重新輸入\n");
            continue;
        }
        if(temp==Temp[5])
        {
            printf("各組增開六獎號碼不可相同,請重新輸入\n");
            continue;
        }
        printf("輸入成功\n");
        Temp[6]=temp;
        for(i=2;i>=0;i--)
        {
            extra[1][i]=temp%10;
            temp=temp/10;
        }
        break;
    }
    while(1)                                                                //設定第三組增開六獎中獎號碼
    {
        printf("請輸入第三組增開六獎中獎號碼\n");
        scanf("%d",&temp);
        if(temp%1000!=temp)
        {
            printf("增開六獎號碼不可大於3位數,請重新輸入\n");
            continue;
        }
        if(temp==Temp[2] || temp==Temp[3] || temp==Temp[4])
        {
            printf("增開六獎不可與頭獎號碼末三碼相同,請重新輸入\n");
            continue;
        }
        if(temp==Temp[5] || temp==Temp[6])
        {
            printf("各組增開六獎號碼不可相同,請重新輸入\n");
            continue;
        }
        printf("輸入成功\n");
        Temp[7]=temp;
        for(i=2;i>=0;i--)
        {
            extra[2][i]=temp%10;
            temp=temp/10;
        }
        break;
    }
    do{
        while(1)
        {
            printf("請輸入一張統一發票號碼\n");
            scanf("%d",&temp);
            if(temp%100000000!=temp)                                                            //判斷發票號碼位數
            {
                printf("統一發票號碼不可大於8位數,請重新輸入\n");
                continue;
            }
            for(i=7;i>=0;i--)                                                                   //存入發票號碼
            {
                receipt[i]=temp%10;
                temp=temp/10;
            }
            break;
        } 
        prize=2;          
        for(i=7;i>=0;i--)                                                                      //判斷是否中特別獎
        {
            if(receipt[i]==special[i])
            {
                prize++;
            }
            else
            {
                prize=1;
                break;
            }
        }
        if(prize==10)
        {
            printf("恭喜你中了特別獎,獎金1000萬!!!\n");
        }
        if(prize==1)                                                                          //判斷是否中特獎
        {
            for(i=7;i>=0;i--)
            {
                if(receipt[i]==spec[i])
                {
                    prize++;
                }
                else
                {
                    prize=0;
                    break;
                }
            }
        }
        if(prize==9)
        {
            printf("恭喜你中了特獎,獎金200萬!!!\n");
        }
        if(prize==0)                                                                          //判斷是否中頭獎
        {
            for(j=0;j<=2;j++)
            {
                prize=0;
                for(i=7;i>=0;i--)
                {
                    if(receipt[i]==head[j][i])
                    {
                        prize++;
                    }
                    else
                    {
                        break;
                    }
                }
                if(prize==8)
                {
                    printf("恭喜你中了頭獎,獎金20萬!!!\n");
                    break;
                }
                if(prize==7)
                {
                    printf("恭喜你中了二獎,獎金4萬元!!!\n");
                    break;
                }
                if(prize==6)
                {
                    printf("恭喜你中了三獎,獎金1萬元!!!\n");
                    break;
                }
                if(prize==5)
                {
                    printf("恭喜你中了四獎,獎金4千元!!!\n");
                    break;
                }
                if(prize==4)
                {
                    printf("恭喜你中了五獎,獎金1千元!!!\n");
                    break;
                }
                if(prize==3)
                {
                    printf("恭喜你中了六獎,獎金2百元!!!\n");
                    break;
                }
            }
        }
        if(prize<3)                                                                          //判斷是否中增開六獎獎
        {
            for(j=0;j<=2;j++)
            {
                prize=0;
                if(receipt[7]==extra[j][2] && receipt[6]==extra[j][1] && receipt[5]==extra[j][0])
                {
                    prize=2;
                    printf("恭喜你中了增開六獎,獎金2百元!!!\n");
                    break;
                }
            }
        }
        if(prize==0)
        {
            printf("下一張就會中了啦QQ\n");
        }
        printf("是否繼續對獎,輸入1繼續對獎,輸入0離開系統\n");
        scanf("%d",&temp);
    }while(temp==1);
    return 0;
}  